# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b957b56e147d077388181ce2c9bf2b692329eb5109defe4f318ba5765877ffffc36968b3da11c271467ff5164277fa3f226d586a7e7963a6bc08f65b73ca1d6

test:
  secret_key_base: 91e405092a81851384f94771e47726e89f9e7faba689d551a546dae5a8231c09c9b2c593ea2475842df5e4c69461dc900593b59ac5756427e5078bdc5475caba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
